version: "3.8"
services:
  db:
    container_name: test-db-server
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: local_loyaltyprogram
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123#
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
          - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql/
    networks:
      test-network:

  adminer:
    container_name: test-adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8892:8080
    networks:
      test-network:
networks:
  test-network: