"""create csv import file

Revision ID: 790b229897e2
Revises: de13d62e4bd8
Create Date: 2024-06-02 15:13:44.798653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790b229897e2'
down_revision: Union[str, None] = 'de13d62e4bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_import_test',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csv_import_test')
    # ### end Alembic commands ###
